{
 "title": "Airflow Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "FRAMEWORK", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Airflow_executor_open_slots",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "airflow_executor_open_slots" }
   ]
  },
  {
   "title": "Airflow Running and Queued Tasks",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "airflow_executor_queued_tasks", "legendFormat": "Airflow Queued Tasks" },
    { "expr": "airflow_executor_running_tasks", "legendFormat": "Airflow Running Tasks" }
   ]
  },
  {
   "title": "airflow_dagbag_import_errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "airflow_dagbag_import_errors", "legendFormat": "Airflow Queued Tasks" }
   ]
  },
  {
   "title": "airflow_ti_successes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "airflow_ti_successes", "legendFormat": "Airflow Queued Tasks" }
   ]
  },
  { "title": "KPI INNER_COMPLIANCE", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Resultados de compliance por estados de interfaces",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  fecha AS metric,\n  sum(ok) AS \"OK\",\n  sum(revisar) AS \"A Revisar\"\nFROM core_history\nWHERE\n  $__timeFilter(fecha)\nGROUP BY fecha,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Resultado de última ejecucón de compiance",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 9 }
  },
  {
   "title": "OK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  sum(ok) AS \"OK\"\nFROM core_history\nGROUP BY fecha\nORDER BY fecha desc\nlimit 1"
    }
   ]
  },
  {
   "title": "A Revisar",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  fecha AS \"time\",\n  sum(revisar) AS \"A Rrvisar\"\nFROM core_history\nGROUP BY fecha\nORDER BY fecha desc\nlimit 1"
    }
   ]
  }
 ]
}