{
 "title": "Airflow Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Airflow_executor_open_slots",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "airflow_executor_open_slots" }
   ]
  },
  {
   "title": "Airflow Running and Queued Tasks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "airflow_executor_queued_tasks", "legendFormat": "Airflow Queued Tasks" },
    { "expr": "airflow_executor_running_tasks", "legendFormat": "Airflow Running Tasks" }
   ]
  },
  {
   "title": "airflow_dagbag_import_errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "airflow_dagbag_import_errors", "legendFormat": "Airflow Queued Tasks" }
   ]
  }
 ]
}