{
 "title": "Airflow Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ne",
    "label": "NE",
    "query": "show tag values from core_history with key=\"ne\""
   }
  ]
 },
 "panels": [
  { "title": "FRAMEWORK", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Airflow_executor_open_slots",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "airflow_executor_open_slots" }
   ]
  },
  {
   "title": "Airflow Running and Queued Tasks",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "airflow_executor_queued_tasks", "legendFormat": "Airflow Queued Tasks" },
    { "expr": "airflow_executor_running_tasks", "legendFormat": "Airflow Running Tasks" }
   ]
  },
  {
   "title": "airflow_dagbag_import_errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "airflow_dagbag_import_errors", "legendFormat": "Airflow Queued Tasks" }
   ]
  },
  {
   "title": "airflow_ti_successes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "airflow_ti_successes", "legendFormat": "Airflow Queued Tasks" }
   ]
  },
  { "title": "KPI INNER_COMPLIANCE", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Resultados de compliance por estados de interfaces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "EvEstado" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "core_history",
     "query": "SELECT sum(\"cantidad\") FROM \"autogen\".\"core_history\" WHERE $timeFilter GROUP BY time($__interval), \"EvEstado\" fill(previous)",
     "select": [
      [
       { "params": [ "cantidad" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ne", "operator": "=~", "value": "/^$ne$/" }
     ]
    }
   ]
  },
  {
   "title": "NE FAILURE",
   "type": "table",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  ne AS FAILURE\nFROM ansible_history"
    }
   ]
  },
  {
   "title": "NE FAILURE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(ne) AS FAILURE\nFROM ansible_history"
    }
   ]
  }
 ]
}